In [1]:
data = [6, 7.5, 8, 0, 1]

In [4]:
import numpy as np
arr1 = np.array(data)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1,2,3,4], [4,5,6,7]]

In [8]:
data2

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [11]:
arr2 = np.array(data2)

In [12]:
arr2.ndim

2

In [13]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int64'))

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
x = np.zeros((3,6))
x.ndim

2

In [17]:
np.empty((2,3,2))

array([[[4.66375073e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])