In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [3]:
obj = Series([4, 7, 5, -3])
obj

0    4
1    7
2    5
3   -3
dtype: int64

In [4]:
obj.values

array([ 4,  7,  5, -3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4, 7, 5, -3], index=['a', 'b', 'c', 'd'])

In [7]:
obj2

a    4
b    7
c    5
d   -3
dtype: int64

In [9]:
obj2.values

array([ 4,  7,  5, -3])

In [10]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
obj2['a']

4

In [14]:
obj2['b'] = 10

In [15]:
obj2

a     4
b    10
c     5
d    -3
dtype: int64

In [17]:
type(obj2[['a', 'b', 'c']])

pandas.core.series.Series

In [18]:
obj2[obj2 > 0]

a     4
b    10
c     5
dtype: int64

In [20]:
obj2 * 2

a     8
b    20
c    10
d    -6
dtype: int64

In [21]:
obj2

a     4
b    10
c     5
d    -3
dtype: int64

In [22]:
np.exp(obj2)

a       54.598150
b    22026.465795
c      148.413159
d        0.049787
dtype: float64

In [23]:
m = {'hao':1, 'shi':2, 'jie':3}

In [24]:
obj3 = Series(m)

In [25]:
obj3

hao    1
jie    3
shi    2
dtype: int64

In [26]:
obj3 * 3

hao    3
jie    9
shi    6
dtype: int64

In [27]:
obj3.isnull()

hao    False
jie    False
shi    False
dtype: bool

In [28]:
obj3.notnull()

hao    True
jie    True
shi    True
dtype: bool

In [16]:
d = {
    'year': ['2000', '2001', '2002'],
    "month": ['10', '11', '12']
}
df = DataFrame(d)
df

month  year
0    10  2000
1    11  2001
2    12  2002

In [5]:
type(df['year'])

pandas.core.series.Series

In [6]:
type(df['month'])

pandas.core.series.Series

In [11]:
df.loc[0]

month      10
year     2000
Name: 0, dtype: object

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [14]:
del df['year']

In [18]:
df.T

0     1     2
month    10    11    12
year   2000  2001  2002

In [19]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [20]:
df.describe()

month  year
count      3     3
unique     3     3
top       12  2002
freq       1     1